# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tap_destination_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
