import type { Metadata } from "next";
import Header from "@/components/header";
import { LocaleProvider } from "@/components/LocaleProvider";
import FloatingChatButton from "@/components/FloatingChatButton";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <main className="flex-1">{children}</main>
      <FloatingChatButton />
    </>
  );
}
