import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { LocaleProvider } from "@/components/LocaleProvider";
import FloatingChatButton from "@/components/FloatingChatButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LocaleProvider>
          <Header />
          <main className="flex-1">{children}</main>
          <footer className="bg-gray-100 p-4 text-center mt-auto">
            © 2025 ShareThings — Inspired by best marketplace UX patterns.
          </footer>
          <FloatingChatButton />
        </LocaleProvider>
        
      </body>
    </html>
  );
}
