# Generated by Django 5.2.7 on 2025-12-31 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0006_reviewvote"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together=set(),
        ),
    ]
