# Generated by Django 5.2.7 on 2026-01-08 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_user_phone_number'),
        ('marketplace', '0007_alter_review_unique_together'),
    ]

    operations = [
    ]
