# Generated by Django 5.2.7 on 2026-01-14 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_merge_20260108_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
