# Generated by Django 5.2.7 on 2026-01-21 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_alter_review_rating'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'listing')},
        ),
    ]
