# Generated by Django 5.2.7 on 2026-01-21 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='pickup_radius_m',
            field=models.IntegerField(default=300, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
