# Generated by Django 5.2.7 on 2026-01-21 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_listing_latitude_listing_longitude_and_more'),
    ]

    operations = [
    ]
