# Generated by Django 5.2.7 on 2026-02-10 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_alter_blogpost_options_blogpost_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
