# Generated by Django 5.2.7 on 2026-02-10 03:28

from django.db import migrations
from django.conf import settings


def update_user_foreign_keys(apps, schema_editor):
    """
    Update all foreign key references from marketplace_user to accounts_user.
    Since User model is now in accounts app, we need to update the table references.
    """
    # For SQLite, we need to recreate tables with new foreign keys
    # But since the User table structure is the same, we can just update the references
    # Actually, Django handles this automatically when AUTH_USER_MODEL changes
    # So we just need to ensure the migration doesn't fail
    pass


def reverse_update_user_foreign_keys(apps, schema_editor):
    """Reverse migration - not needed since we're removing marketplace.User"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_alter_blogpost_options_blogpost_category_and_more'),
        ('accounts', '0001_initial'),  # Ensure accounts.User exists first
    ]

    operations = [
        # User model is now in accounts app, so we just remove it from marketplace
        # The foreign keys will automatically point to accounts_user since AUTH_USER_MODEL is set
        migrations.RunPython(update_user_foreign_keys, reverse_update_user_foreign_keys),
        migrations.DeleteModel(
            name='User',
        ),
    ]
