# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0021_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="stripe_payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
