# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0022_booking_payment_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Inactive listings are hidden from search and public detail; owner can still see and reactivate.",
            ),
        ),
    ]
