# Generated by Django 5.2.7 on 2026-02-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_participantlastread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_ACCEPTED', 'Booking accepted'), ('BOOKING_DECLINED', 'Booking declined'), ('BOOKING_CANCELLED', 'Booking cancelled'), ('NEW_MESSAGE', 'New message')], max_length=30),
        ),
    ]
