# Generated by Django 5.2.7 on 2026-07-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_message_file_message_latitude_message_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
