# Generated by Django 5.2.7 on 2026-07-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0030_message_audio_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='owner_completion_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BOOKING_ACCEPTED', 'Booking accepted'), ('BOOKING_DECLINED', 'Booking declined'), ('BOOKING_CANCELLED', 'Booking cancelled'), ('NEW_MESSAGE', 'New message'), ('PAYMENT_RECEIVED', 'Payment received'), ('RENTAL_COMPLETED', 'Rental completed')], max_length=30),
        ),
    ]
