# Generated by Django 5.2.7 on 2026-07-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0031_booking_owner_completion_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
